### ISSUE TITLE
关于这个宏文件

### ISSUE THREAD

**Issue by foreverlong** [MountCloud/FPSLogitechForceGunMacro#1]
首先感谢作者写出的宏文件
不知道是我的配置出错了还是什么，这个宏文件确实能够使鼠标向下移动，但并不是匀速移动的，是变速移动的，移动速度越来越快，而且是很明显的是个加速度，不过找了半天代码里的问题并没有找到 希望可以优化一下 谢谢

**Comment by MountCloud** [comment]
increment是加速比，0就不加速了。

**Comment by MountCloud** [comment]
长时间没有收到回复于是关闭这个lssues
